# Generated by Django 4.2.3 on 2023-08-05 11:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("internapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="contributors",
            field=models.ManyToManyField(
                related_name="contributors", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
